#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""render_config.py — the registry-to-LiteLLM-config renderer (HB-0 Step 1).

registry.yaml is the single source of truth for a deployment. This script
validates it against schema/registry.schema.json, then renders a LiteLLM
config using the `include:` directive for the model list:

    <out-dir>/config.yaml               settings (router/litellm/general) +
                                         `include: [model_list.generated.yaml]`
    <out-dir>/model_list.generated.yaml  the model_list, derived from registry.yaml

Both output files carry a "GENERATED — do not hand-edit" header. Re-run this
script to apply a registry change; do not hand-edit the rendered files.

Two invocations:

  Live render (run from portage-local):
    uv run --with pyyaml --with jsonschema python src/portage/render_config.py \\
        --registry ../portage-local/registry.yaml \\
        --settings ../portage-local/litellm_settings.yaml \\
        --schema schema/registry.schema.json \\
        --out-dir ../portage-local/litellm

  CI / example re-render check (run from the engine repo):
    python src/portage/render_config.py \\
        --registry config/profiles/scale1.example.registry.yaml \\
        --settings config/profiles/scale1.example.settings.yaml \\
        --schema schema/registry.schema.json \\
        --out-dir config/profiles --check \\
        --config-name scale1.example.yaml \\
        --model-list-name scale1.example.model_list.yaml

`--check` renders into memory and diffs against the existing files at
`--out-dir` instead of writing — it exits non-zero and never modifies the
previous config on any schema violation or diff.

Refuses to render on any schema violation. Never writes a partial file: both
outputs are built in memory first and only written once everything validates.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml
from jsonschema import Draft7Validator

ALIASES = (
    "classifier",
    "code_small",
    "code_large",
    "research_synthesis",
    "embedding",
    "proprietary_code",
    "proprietary_research",
)

GENERATED_HEADER = (
    "# GENERATED by src/portage/render_config.py from registry.yaml — do not\n"
    "# hand-edit. Re-run the renderer to apply a registry change. A CI check\n"
    "# re-renders and diffs this file against its source on every PR.\n"
)


class RegistryError(Exception):
    """A registry failed validation. Carries every problem found, not just the first."""


def load_yaml(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def validate_schema(registry: dict, schema: dict) -> list[str]:
    validator = Draft7Validator(schema)
    errors = sorted(validator.iter_errors(registry), key=lambda e: list(e.path))
    return [
        f"{'/'.join(str(p) for p in e.path) or '<root>'}: {e.message}" for e in errors
    ]


def validate_cross_entry(models: list[dict]) -> list[str]:
    """Checks JSON Schema can't express: alias grouping, order uniqueness,
    duplicate-alias order requirements."""
    problems = []
    by_alias: dict[str, list[dict]] = {}
    for i, m in enumerate(models):
        alias = m.get("alias")
        if alias not in ALIASES:
            problems.append(
                f"models[{i}]: alias {alias!r} is not one of the seven fixed aliases"
            )
        by_alias.setdefault(alias, []).append(m)

    for alias, entries in by_alias.items():
        enabled_entries = [e for e in entries if e.get("enabled")]
        if len(enabled_entries) > 1:
            orders = [e.get("order") for e in enabled_entries]
            if any(o is None for o in orders):
                problems.append(
                    f"alias {alias!r}: {len(enabled_entries)} enabled entries but "
                    "at least one has no `order` — required for disambiguation "
                    "once an alias has more than one enabled deployment"
                )
            elif len(set(orders)) != len(orders):
                problems.append(
                    f"alias {alias!r}: duplicate `order` values among enabled "
                    f"entries: {orders}"
                )
        for e in entries:
            if e.get("provider_route") == "ollama_chat" and not e.get("endpoint"):
                problems.append(
                    f"alias {alias!r} model_id {e.get('model_id')!r}: provider_route "
                    "ollama_chat requires `endpoint`"
                )
    return problems


def render_model_list(models: list[dict]) -> dict:
    """Registry entries -> a LiteLLM `model_list`. Every entry renders,
    enabled or not — Gate 2 requires /v1/models to list exactly the seven
    aliases, so a disabled alias still needs to be visible there. `enabled`
    is carried into model_info instead: HB-2's rescue path flips that flag
    (and provisions the real secret) rather than adding config, and it's
    also downstream tooling's (failup.py/herdr-meters) signal not to select
    a disabled deployment. Exclusion-from-registration was tried first and
    was wrong: it silently dropped two of the seven aliases from /v1/models,
    which is exactly what Gate 2 checks for."""
    model_list = []
    for m in models:
        route = m["provider_route"]
        model_id = m["model_id"]
        litellm_params: dict = {}
        if route == "ollama_chat":
            litellm_params["model"] = f"ollama_chat/{model_id}"
            litellm_params["api_base"] = m["endpoint"]
        elif route == "openrouter":
            litellm_params["model"] = f"openrouter/{model_id}"
            litellm_params["api_key"] = "os.environ/OPENROUTER_API_KEY"
        elif route == "anthropic":
            litellm_params["model"] = f"anthropic/{model_id}"
            litellm_params["api_key"] = "os.environ/ANTHROPIC_API_KEY"
        elif route == "perplexity":
            litellm_params["model"] = f"perplexity/{model_id}"
            litellm_params["api_key"] = "os.environ/PERPLEXITYAI_API_KEY"
        elif route == "openai":
            # Scale-2's institution-hosted vLLM. NOT api.openai.com — see
            # `openai_direct` below. The two are separate enum values on
            # purpose: collapsing them would sign a commercial OpenAI call
            # with the sovereign token, or point GPT-5.6 Sol at Jetstream2.
            litellm_params["model"] = f"openai/{model_id}"
            litellm_params["api_base"] = m.get(
                "endpoint", "os.environ/SOVEREIGN_BASE_URL"
            )
            litellm_params["api_key"] = "os.environ/SOVEREIGN_TOKEN"
        elif route == "openai_direct":
            litellm_params["model"] = f"openai/{model_id}"
            litellm_params["api_key"] = "os.environ/OPENAI_API_KEY"
        elif route == "deepseek":
            # First-party api.deepseek.com, not an aggregator: CW-04 §2.2 makes
            # this rung direct specifically for automatic prefix caching, which
            # bills a repeated prefix at ~2% of the miss rate. A native LiteLLM
            # provider in the pinned v1.93.0, so no api_base is needed.
            litellm_params["model"] = f"deepseek/{model_id}"
            litellm_params["api_key"] = "os.environ/DEEPSEEK_API_KEY"
        elif route == "morph":
            litellm_params["model"] = f"morph/{model_id}"
            litellm_params["api_key"] = "os.environ/MORPH_API_KEY"
        elif route == "moonshot":
            litellm_params["model"] = f"moonshot/{model_id}"
            litellm_params["api_key"] = "os.environ/MOONSHOT_API_KEY"
        else:  # pragma: no cover - schema enum already prevents this
            raise RegistryError(f"unknown provider_route {route!r}")

        if m.get("order") is not None:
            litellm_params["order"] = m["order"]
        # `effort` is the registry's field name (matching models.json on Lane A);
        # `reasoning_effort` is LiteLLM's param name. Omitted entirely when null,
        # never sent as a default — a rung that wants default effort must not
        # carry the flag at all (same rule as failup.py's tiers file).
        if m.get("effort") is not None:
            litellm_params["reasoning_effort"] = m["effort"]

        model_info = {
            "portage_alias": m["alias"],
            "enabled": m["enabled"],
            "open_weight": m["open_weight"],
            "license": m["license"],
            "license_family": m["license_family"],
            "max_context": m["max_context"],
            "supports_tools": m["supports_tools"],
            "supports_json": m["supports_json"],
            "data_classification": m["data_classification"],
            "benchmark_version": m.get("benchmark_version"),
            "bfclv3": m.get("bfclv3"),
            "ifeval": m.get("ifeval"),
        }
        if "thinking_disabled_for_structured" in m:
            model_info["thinking_disabled_for_structured"] = m[
                "thinking_disabled_for_structured"
            ]
        if "stream_tools" in m:
            model_info["stream_tools"] = m["stream_tools"]
        if m.get("effort") is not None:
            model_info["effort"] = m["effort"]
        # Only surfaced when true. These are policy markers a downstream
        # selector reads (the same way it reads `enabled`), so an absent key
        # and an explicit false mean the same thing and the noise isn't worth
        # carrying on every row.
        if m.get("fable_tier"):
            model_info["fable_tier"] = True
        if m.get("failover_only"):
            model_info["failover_only"] = True

        model_list.append(
            {
                "model_name": m["alias"],
                "litellm_params": litellm_params,
                "model_info": model_info,
            }
        )
    return {"model_list": model_list}


def build_outputs(
    registry: dict, settings: dict, model_list_name: str
) -> tuple[str, str]:
    """Returns (config_yaml_text, model_list_yaml_text)."""
    model_list_doc = render_model_list(registry["models"])
    model_list_text = GENERATED_HEADER + "\n" + yaml.safe_dump(
        model_list_doc, sort_keys=False, default_flow_style=False
    )

    config_doc = dict(settings)
    config_doc["include"] = [model_list_name]
    config_text = GENERATED_HEADER + "\n" + yaml.safe_dump(
        config_doc, sort_keys=False, default_flow_style=False
    )
    return config_text, model_list_text


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--registry", required=True, type=Path)
    p.add_argument("--settings", required=True, type=Path)
    p.add_argument("--schema", required=True, type=Path)
    p.add_argument("--out-dir", required=True, type=Path)
    p.add_argument("--config-name", default="config.yaml")
    p.add_argument("--model-list-name", default="model_list.generated.yaml")
    p.add_argument(
        "--check",
        action="store_true",
        help="Diff against existing output instead of writing; nonzero on any diff.",
    )
    args = p.parse_args(argv)

    try:
        registry = load_yaml(args.registry)
        schema = json.loads(args.schema.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError, json.JSONDecodeError) as e:
        print(f"render_config: could not load input files: {e}", file=sys.stderr)
        return 1

    schema_errors = validate_schema(registry, schema)
    if schema_errors:
        print(
            "render_config: registry FAILED schema validation. No output written.",
            file=sys.stderr,
        )
        for e in schema_errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    cross_errors = validate_cross_entry(registry["models"])
    if cross_errors:
        print(
            "render_config: registry FAILED cross-entry validation. "
            "No output written.",
            file=sys.stderr,
        )
        for e in cross_errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    settings = load_yaml(args.settings)
    config_text, model_list_text = build_outputs(registry, settings, args.model_list_name)

    config_path = args.out_dir / args.config_name
    model_list_path = args.out_dir / args.model_list_name

    if args.check:
        diffs = []
        outputs = ((config_path, config_text), (model_list_path, model_list_text))
        for path, new_text in outputs:
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != new_text:
                diffs.append(str(path))
        if diffs:
            print(
                f"render_config --check: re-render differs from committed output: "
                f"{diffs}",
                file=sys.stderr,
            )
            print("Run the renderer and commit the result.", file=sys.stderr)
            return 1
        print("render_config --check: up to date.")
        return 0

    args.out_dir.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_text, encoding="utf-8")
    model_list_path.write_text(model_list_text, encoding="utf-8")

    enabled = sum(1 for m in registry["models"] if m.get("enabled"))
    disabled = len(registry["models"]) - enabled
    per_alias = {}
    for m in registry["models"]:
        if m.get("enabled"):
            per_alias[m["alias"]] = per_alias.get(m["alias"], 0) + 1
    print(f"render_config: wrote {config_path} and {model_list_path}")
    print(
        f"render_config: {enabled} enabled deployment(s), {disabled} disabled, "
        f"across {len(per_alias)} alias(es): {per_alias}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
